### ISSUE TITLE
取得エラー

### ISSUE THREAD

**Issue by detianitatibs** [detianitatibs/BASBI#3]
- たまにタイムアウトが発生する
- 以下のような取得エラーが発生する(一部マスキング)
```
4094
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:58296/devtools/browser/7572d2bc-cb2d-4efa-b274-547c546a213b
ERROR:src.adapter.stats.controller.collect_stats_controller:failed scraping from html: Navigation Timeout Exceeded: 8000 ms exceeded.
Traceback (most recent call last):
  File "data_collect/src/bin/bleague_collect_stats.py", line 25, in <module>
    controller.collect(schedule_key=args.schedule_key)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 38, in collect
    game_info_inputdata = self._find_game_info(schedule_key, r_html)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 114, in _find_game_info
    quarter_score_home = tr.find('td.quarter_score.home', first=True).text
AttributeError: 'NoneType' object has no attribute 'text'
```

```
4113
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:59273/devtools/browser/a28e1dcd-5cc3-4c40-9f64-4970f9eacf35
INFO:src.adapter.stats.controller.collect_stats_controller:success scraping from html: https://www.bleague.jp/game_detail/?ScheduleKey=4113
Traceback (most recent call last):
  File "data_collect/src/bin/bleague_collect_stats.py", line 25, in <module>
    controller.collect(schedule_key=args.schedule_key)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 38, in collect
    game_info_inputdata = self._find_game_info(schedule_key, r_html)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 113, in _find_game_info
    quarter_name = tr.find('span.name', first=True).text
AttributeError: 'NoneType' object has no attribute 'text'
```

```
4118
[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:59527/devtools/browser/0fd9bf36-5cc9-4de4-abd0-51a48bc1013a
INFO:src.adapter.stats.controller.collect_stats_controller:success scraping from html: https://www.bleague.jp/game_detail/?ScheduleKey=4118
Traceback (most recent call last):
  File "data_collect/src/bin/bleague_collect_stats.py", line 25, in <module>
    controller.collect(schedule_key=args.schedule_key)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 38, in collect
    game_info_inputdata = self._find_game_info(schedule_key, r_html)
  File "data_collect/src/adapter/stats/controller/collect_stats_controller.py", line 122, in _find_game_info
    list_score_home.append(int(quarter_score_home))
ValueError: invalid literal for int() with base 10: ''
[I:pyppeteer.launcher] terminate chrome process...
```

**Comment by detianitatibs** [comment]
- 4094
`td.quarter_score.home`と`td.quarter_score.away`が`td.quarter_score.Home`と`td.quarter_score.Away`のケースがあったので、対応できるように修正
- 4113
試合情報が無い(フォーマットのみ)ケースがあったので、その場合はデータを取得しないように修正
- 4118
プレーオフ第3戦で2Qまでしない場合に3,4Qに不要な空白がありエラーとなっていたので、処理をスキップするように修正

**Comment by detianitatibs** [comment]
タイムアウトする問題については、標準は8秒過ぎたら発生するので、60秒に変更した
[参考](https://laboratory.kazuuu.net/install-requests-html-that-can-parse-html-as-simply-as-possible-windows10/#toc4)
